/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as CrearRouteImport } from './routes/crear'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesGameIdIndexRouteImport } from './routes/_games/$gameId/index'
import { Route as GamesGameIdEditRouteImport } from './routes/_games/$gameId/edit'

const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const CrearRoute = CrearRouteImport.update({
  id: '/crear',
  path: '/crear',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGameIdIndexRoute = GamesGameIdIndexRouteImport.update({
  id: '/_games/$gameId/',
  path: '/$gameId/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGameIdEditRoute = GamesGameIdEditRouteImport.update({
  id: '/_games/$gameId/edit',
  path: '/$gameId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crear': typeof CrearRoute
  '/favoritos': typeof FavoritosRoute
  '/$gameId/edit': typeof GamesGameIdEditRoute
  '/$gameId': typeof GamesGameIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crear': typeof CrearRoute
  '/favoritos': typeof FavoritosRoute
  '/$gameId/edit': typeof GamesGameIdEditRoute
  '/$gameId': typeof GamesGameIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/crear': typeof CrearRoute
  '/favoritos': typeof FavoritosRoute
  '/_games/$gameId/edit': typeof GamesGameIdEditRoute
  '/_games/$gameId/': typeof GamesGameIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/crear' | '/favoritos' | '/$gameId/edit' | '/$gameId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/crear' | '/favoritos' | '/$gameId/edit' | '/$gameId'
  id:
    | '__root__'
    | '/'
    | '/crear'
    | '/favoritos'
    | '/_games/$gameId/edit'
    | '/_games/$gameId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CrearRoute: typeof CrearRoute
  FavoritosRoute: typeof FavoritosRoute
  GamesGameIdEditRoute: typeof GamesGameIdEditRoute
  GamesGameIdIndexRoute: typeof GamesGameIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crear': {
      id: '/crear'
      path: '/crear'
      fullPath: '/crear'
      preLoaderRoute: typeof CrearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_games/$gameId/': {
      id: '/_games/$gameId/'
      path: '/$gameId'
      fullPath: '/$gameId'
      preLoaderRoute: typeof GamesGameIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_games/$gameId/edit': {
      id: '/_games/$gameId/edit'
      path: '/$gameId/edit'
      fullPath: '/$gameId/edit'
      preLoaderRoute: typeof GamesGameIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CrearRoute: CrearRoute,
  FavoritosRoute: FavoritosRoute,
  GamesGameIdEditRoute: GamesGameIdEditRoute,
  GamesGameIdIndexRoute: GamesGameIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
