/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as CrearRouteImport } from './routes/crear'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesGameIdRouteImport } from './routes/_games/$gameId'
import { Route as GamesGameIdEditRouteImport } from './routes/_games/$gameId.edit'

const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const CrearRoute = CrearRouteImport.update({
  id: '/crear',
  path: '/crear',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGameIdRoute = GamesGameIdRouteImport.update({
  id: '/_games/$gameId',
  path: '/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGameIdEditRoute = GamesGameIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => GamesGameIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crear': typeof CrearRoute
  '/favoritos': typeof FavoritosRoute
  '/$gameId': typeof GamesGameIdRouteWithChildren
  '/$gameId/edit': typeof GamesGameIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crear': typeof CrearRoute
  '/favoritos': typeof FavoritosRoute
  '/$gameId': typeof GamesGameIdRouteWithChildren
  '/$gameId/edit': typeof GamesGameIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/crear': typeof CrearRoute
  '/favoritos': typeof FavoritosRoute
  '/_games/$gameId': typeof GamesGameIdRouteWithChildren
  '/_games/$gameId/edit': typeof GamesGameIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/crear' | '/favoritos' | '/$gameId' | '/$gameId/edit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/crear' | '/favoritos' | '/$gameId' | '/$gameId/edit'
  id:
    | '__root__'
    | '/'
    | '/crear'
    | '/favoritos'
    | '/_games/$gameId'
    | '/_games/$gameId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CrearRoute: typeof CrearRoute
  FavoritosRoute: typeof FavoritosRoute
  GamesGameIdRoute: typeof GamesGameIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crear': {
      id: '/crear'
      path: '/crear'
      fullPath: '/crear'
      preLoaderRoute: typeof CrearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_games/$gameId': {
      id: '/_games/$gameId'
      path: '/$gameId'
      fullPath: '/$gameId'
      preLoaderRoute: typeof GamesGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_games/$gameId/edit': {
      id: '/_games/$gameId/edit'
      path: '/edit'
      fullPath: '/$gameId/edit'
      preLoaderRoute: typeof GamesGameIdEditRouteImport
      parentRoute: typeof GamesGameIdRoute
    }
  }
}

interface GamesGameIdRouteChildren {
  GamesGameIdEditRoute: typeof GamesGameIdEditRoute
}

const GamesGameIdRouteChildren: GamesGameIdRouteChildren = {
  GamesGameIdEditRoute: GamesGameIdEditRoute,
}

const GamesGameIdRouteWithChildren = GamesGameIdRoute._addFileChildren(
  GamesGameIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CrearRoute: CrearRoute,
  FavoritosRoute: FavoritosRoute,
  GamesGameIdRoute: GamesGameIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
